Metatavu/kunta-api-server

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/cache/AnnouncementCache.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/AnnouncementController.java
src/main/java/fi/otavanopisto/kuntaapi/server/discover/AnnouncementIdRemoveRequest.java
src/main/java/fi/otavanopisto/kuntaapi/server/discover/AnnouncementIdUpdateRequest.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/AbstractManagementProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementAnnouncementEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementAnnouncementIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementAnnouncementProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementApi.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementClient.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementMenuEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementMenuIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsArticleEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsArticleIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java

Feature #107 announcements

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTranslator.java

Fixed issue #1

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/AbstractManagementProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementAnnouncementEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementAnnouncementIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsArticleEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsArticleIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileIdUpdater.java

Upgraded management rest client to 0.0.24 (supports wp 4.7)

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/HttpCacheController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/PageController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMCache.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMCacheUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMPageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageProvider.java
src/test/java/fi/otavanopisto/kuntaapi/test/AbstractIntegrationTest.java

Changed not synchronized and non existing contents to return empty
collection instead of null when node itself exists in CaseM and
management page providers
Resolves #24

Fixed issue #24

---

src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/AbstractDAO.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/IdentifierDAO.java

Changed IdentifierDAO to use getSingleResult in
findOrderIndexByKuntaApiIdentifier
Resolves #27

Fixed issue #27

---

src/main/java/fi/otavanopisto/kuntaapi/server/cache/SystemController.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/SystemRESTService.java

Added cache check into /system/ping check

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IdentifierController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMAttachmentEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMCacheUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMMeetingEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/kuntarekry/KuntaRekryOrganizationJobsEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementAnnouncementEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementMenuEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsArticleEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvOrganizationEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvOrganizationServiceIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceElectronicChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/ServiceLocationChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/ServicePhoneChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/ServicePrintableFormChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/ServiceWebPageChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/vcard/VCardEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/IdentifierDAO.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/model/Identifier.java
src/main/resources/fi/otavanopisto/kuntaapi/server/liquibase/changelog.xml

Feature #6 identifier relations

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IdentifierController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMPageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/IdentifierDAO.java

Feature #34 parent lookups

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/EntityController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IdentifierController.java
src/main/java/fi/otavanopisto/kuntaapi/server/debug/Timed.java
src/main/java/fi/otavanopisto/kuntaapi/server/debug/TimedInterceptor.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMCacheUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMPageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/IdentifierDAO.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/model/IdentifierOrderIndex.java
src/main/resources/fi/otavanopisto/kuntaapi/server/liquibase/changelog.xml
src/main/webapp/WEB-INF/beans.xml

Hotfix #51 multiple pages

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/BinaryHttpClient.java

Added status code check into BinaryHttpClient getDownloadMeta method

---

src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexRemovePage.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java

Added support for indexing management page contents

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IdentifierController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageProvider.java

Finalized page image type

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/cache/AbstractPageIdMapCache.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IdMapController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/IdMapProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMCacheUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementIdMapProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageIdMapEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/cache/ManagementPageIdMapCache.java

Feature #82 page mappings

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IdentifierController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsArticleEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsArticleIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/IdentifierDAO.java

Fixed issue with removing news images

---

src/main/java/fi/otavanopisto/kuntaapi/server/cache/AbstractCache.java
src/main/java/fi/otavanopisto/kuntaapi/server/cache/AbstractPageIdMapCache.java
src/main/java/fi/otavanopisto/kuntaapi/server/id/IdSerializer.java
src/main/java/fi/otavanopisto/kuntaapi/server/infinispan/IdKey2StringMapper.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/IdMapProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementIdMapProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageIdMapEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/cache/ManagementAttachmentCache.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytAttachmentCache.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/jackson/IdDeserializer.java
src/main/java/fi/otavanopisto/kuntaapi/server/jackson/IdKeyDeserializer.java
src/main/java/fi/otavanopisto/kuntaapi/server/jackson/IdKeySerializer.java
src/main/java/fi/otavanopisto/kuntaapi/server/jackson/IdModule.java
src/main/java/fi/otavanopisto/kuntaapi/server/jackson/IdSerializer.java

Hotfix #93 event images

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageIdUpdater.java

Changed management pages to be loaded paged

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/AbstractManagementProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsArticleEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTranslator.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/management/PageTestsIT.java

Hotfix #99 attachment types

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IdentifierRelationController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMCacheUpdater.java

Changed casem to use original parent page title instead of mapped one

---

travis.sh

Changed travis build to resolve pom version with sed

---

src/main/java/fi/otavanopisto/kuntaapi/server/tasks/AbstractTaskQueue.java

Removed batch from task queue tasks cache

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsArticleEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/webhooks/ManagementWebhookHandler.java

Fixed issue #116

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IdentifierRelationController.java

Fixed issue #119

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMMeetingEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMOrganizationContentsEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/GtfsIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvOrganizationIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceIdUpdater.java

Updated timers

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/AnnouncementController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/ContactController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/FragmentController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/JobController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/NewsController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/OrganizationController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/PageController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/PublicTransportController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/ServiceController.java
src/main/java/fi/otavanopisto/kuntaapi/server/utils/ListUtils.java

Changed result lists to be sorted first and limited afterwards

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/EntityController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/PublicTransportController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/PublicTransportProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/PublicTransportStopTimeSortBy.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/SortDir.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/GtfsPublicTransportProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/gtfs/StopTimeTestsIT.java

Feature #131 stop time filters

---

src/main/java/fi/otavanopisto/kuntaapi/server/tasks/AbstractTaskQueue.java

Added init and destroy listeners into abstract task queue

---

src/main/resources/fi/otavanopisto/kuntaapi/server/integrations/casem/content-meeting-item.ftlh

Added css class into history topics

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/GtfsStopTimeEntityUpdater.java

Added organizationId into stop time index

---

src/main/java/fi/otavanopisto/kuntaapi/server/index/StopTimeSearcher.java

Fixed NPE on StopTimeSearcher

---

src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexUpdater.java

Resolves #151

---

src/main/java/fi/otavanopisto/kuntaapi/server/discover/EntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/discover/IdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/SystemRESTService.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/AbstractTaskQueue.java

Added support for stopping task queues and updaters via REST calls

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/PublicTransportController.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java

Added support for limiting transport stoptimes by first and max results

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/KuntaApiIdFactory.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/GtfsIdFactory.java

Added ApplicationScoped into KuntaApiIdFactory

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IdentifierRelationController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/GtfsRouteEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/GtfsScheduleEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/GtfsStopEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/GtfsStopTimeEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/GtfsTripEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/model/IdentifierRelation.java

Added null-checks into gtfs entity updaters

---

src/main/java/fi/otavanopisto/kuntaapi/server/tasks/AbstractTaskQueue.java

Removed manual batching from AbstractTaskQueue

---

src/main/java/fi/otavanopisto/kuntaapi/server/cache/AbstractCache.java
src/main/java/fi/otavanopisto/kuntaapi/server/cache/AbstractEntityCache.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/StoredResourceController.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/StoredResourceDAO.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/model/StoredResource.java
src/main/resources/fi/otavanopisto/kuntaapi/server/liquibase/changelog.xml
src/test/java/fi/otavanopisto/kuntaapi/test/AbstractTest.java

Initial version of StoredResources

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/ClusterController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/TaskController.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/TaskDAO.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/TaskQueueDAO.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/model/Task.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/model/TaskQueue.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/AbstractTaskQueue.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/TaskQueueDistributor.java
src/main/resources/fi/otavanopisto/kuntaapi/server/liquibase/changelog.xml
src/main/webapp/WEB-INF/jboss-deployment-structure.xml

Feature #185 distributed task queues

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMCacheUpdater.java

Fixes #189

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/TaskController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvOrganizationServiceIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceElectronicChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceLocationChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServicePhoneChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServicePrintableFormChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceWebPageChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/AbstractTaskQueue.java

Hotfix #200 not responsible new tasks

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/model/HistoryTopic.java

Changed casem to ignore unknown history topic properties

---

src/main/java/fi/otavanopisto/kuntaapi/server/discover/EntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/discover/IdUpdater.java

Changed timers to be persistent

---

src/main/java/fi/otavanopisto/kuntaapi/server/discover/EntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/discover/IdUpdater.java

Wrapped timer value getters into try catches

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/TaskController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytEntityUpdater.java

Hotfix #213 mikkelinyt duplicate tasks

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IdentifierController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvOrganizationIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceIdRemoveUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/IdentifierDAO.java

Feature #191 service id updaters

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/TaskController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/GtfsIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/kuntarekry/KuntaRekryJobIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementAnnouncementIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementFragmentIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementMenuIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsArticleIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementRemovedPageIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementShortlinkIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvOrganizationServiceIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceElectronicChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceLocationChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServicePhoneChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServicePrintableFormChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceWebPageChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/TaskDAO.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/AbstractTaskQueue.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/management/PageTestsIT.java

Create new id tasks only if queue is empty

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/GtfsIdTaskPersistor.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/GtfsIdUpdater.java

Use separate gtfs task persistor

---

src/main/java/fi/otavanopisto/kuntaapi/server/id/AbstractIdFactory.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementIdFactory.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/webhooks/ManagementWebhookHandler.java
src/main/java/fi/otavanopisto/kuntaapi/server/webhooks/WebHookServlet.java

Feature #235 management menu webhooks

---

src/main/java/fi/otavanopisto/kuntaapi/server/id/AbstractIdFactory.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/webhooks/ManagementWebhookHandler.java

Added webhook handlers for shortlinks and fragments

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/TaskController.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/TaskQueueDAO.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/model/TaskQueue.java
src/main/resources/fi/otavanopisto/kuntaapi/server/liquibase/changelog.xml

Added column for storing timestamp when last task was returned into task

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/kuntarekry/KuntaRekryJobEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/kuntarekry/KuntaRekryJobIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/kuntarekry/tasks/AbstractKuntaRekryJobTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/kuntarekry/tasks/KuntaRekryJobEntityTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/kuntarekry/tasks/KuntaRekryJobTaskQueue.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/kuntarekry/tasks/KuntaRekryRemoveJobTask.java

Feature #221 job removal

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/id/AbstractIdFactory.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementConsts.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/main/webapp/WEB-INF/jboss-deployment-structure.xml
src/test/java/fi/otavanopisto/kuntaapi/test/AbstractIntegrationTest.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/management/PageTestsIT.java
src/test/resources/management/pages/456.json

Feature #70 management content images

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/StoredResourceController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/AbstractManagementProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsArticleEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/resources/ManagementAttachmentDataResourceContainer.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/StoredBinaryResourceDAO.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/model/StoredBinaryResource.java
src/main/java/fi/otavanopisto/kuntaapi/server/resources/AbstractAttachmentDataResourceContainer.java
src/main/java/fi/otavanopisto/kuntaapi/server/resources/AbstractBinaryResourceContainer.java
src/main/java/fi/otavanopisto/kuntaapi/server/resources/AbstractResourceContainer.java
src/main/java/fi/otavanopisto/kuntaapi/server/resources/AbstractResourceContainerBase.java
src/main/java/fi/otavanopisto/kuntaapi/server/resources/StoredBinaryData.java
src/main/resources/fi/otavanopisto/kuntaapi/server/liquibase/changelog.xml
src/test/java/fi/otavanopisto/kuntaapi/test/AbstractTest.java

Feature #244 image resource containers

---

src/main/java/fi/otavanopisto/kuntaapi/server/images/ImageWriter.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/AbstractManagementProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytEventProvider.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/management/BannerTestsIT.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/management/PageTestsIT.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/management/PostTestsIT.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/management/TileTestsIT.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integrations/mikkelinyt/MikkeliNytRestTestsIT.java

Feature #246 scaled image format

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/ServiceController.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexRemoveServiceLocationServiceChannel.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexableServiceLocationServiceChannel.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/ServiceLocationServiceChannelSearcher.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServiceChannelEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/ServiceLocationServiceChannelsApiImpl.java
src/main/java/fi/otavanopisto/kuntaapi/server/utils/LocalizationUtils.java

Added support for searching service location channels

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/AbstractPtvOrganizationIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/AbstractPtvServiceChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/AbstractPtvServiceIdUpdater.java

Added null checks to AbstractPtvIdUpdaters

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvOrganizationPriorityIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServiceChannelPriorityIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServicePriorityIdUpdater.java

Fixed #256

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/servicechannels/PtvServiceChannelResolver.java

Added null check to serviceChannelData

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServiceChannelIdUpdater.java

Fixed #261

---

src/main/java/fi/otavanopisto/kuntaapi/server/discover/EntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/discover/EntityUpdaterInitializer.java
src/main/java/fi/otavanopisto/kuntaapi/server/discover/IdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/discover/IdUpdaterInitializer.java
src/main/java/fi/otavanopisto/kuntaapi/server/discover/SchedulerIntervalUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvOrganizationPriorityIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServiceChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServiceChannelPriorityIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServicePriorityIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/settings/SystemSettingController.java
src/test/java/fi/otavanopisto/kuntaapi/test/AbstractPtvMocker.java

Hotfix #263 scheduler timeout failures

---

src/main/java/fi/otavanopisto/kuntaapi/server/tasks/AbstractTaskQueue.java

Improved logging

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/webhooks/ManagementWebhookHandler.java

Added management announcement webhook support

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/MenuController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementMenuEntityUpdater.java

Resolves #274

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/GenericHttpClient.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementAnnouncementIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementClient.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementFragmentIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementMenuIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsArticleIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementRemovedPageIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementShortlinkIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileIdUpdater.java

Added support for HEAD requests.

---

src/main/java/fi/otavanopisto/kuntaapi/server/rest/SystemRESTService.java

Added health details for unknown updaters into updater health endpoint

---

pom.xml

Changed jacoco to exlude all classes with _ -postfix

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/NewsController.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/NewsArticleSearcher.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java

Added support for searching news articles

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IdentifierController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementRemovedPageIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/IdentifierDAO.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/AbstractOrganizationEntityTaskQueue.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/OrganizationEntityUpdateTask.java

Changed removed management pages to be checked in pages

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServiceEntityUpdater.java

Fixed #302

---

src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/ptv/OrganizationsTestsIT.java

Hotfix #306 organization business searches

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementIncidentProvider.java

Fixed #309

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytEventProvider.java

Added a null-check into mikkeli nyt image scaler

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/tilannehuone/updaters/TilannehuoneIdUpdater.java

Added time limit into TilannehuoneIdUpdater

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/webhooks/ManagementWebhookHandler.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/webhooks/Payload.java

Changed management webhooks to handle orderIndices

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytEventProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytImageLoader.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/resources/MikkeliNytAttachmentDataResourceContainer.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/resources/MikkeliNytAttachmentResourceContainer.java

Changed mikkeli nyt to use stored binaries

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytImageLoader.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integrations/mikkelinyt/MikkeliNytRestTestsIT.java

Changed mikkeli nyt to check image sizes 1140 and 1000

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTranslator.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/management/IncidentTestsIT.java
src/test/resources/management/incidents/10001.json
src/test/resources/management/incidents/10002.json
src/test/resources/management/incidents/10003.json

Added support for details links into management incidents

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/EmergencyController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/EventController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/FragmentController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IncidentController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/ShortlinkController.java
src/test/java/fi/otavanopisto/kuntaapi/test/AbstractTest.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/tilannehuone/TilannehuoneTestsIT.java
src/test/resources/tilannehuone/tilannehuone.json

Hotfix #332 emergency list order

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/PageController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/PageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMPageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java

Added support for removing casem pages

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvOrganizationPriorityIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServiceChannelPriorityIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServicePriorityIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/tilannehuone/updaters/TilannehuoneIdUpdater.java

Fixed issue #341

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IdentifierRelationController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServiceChannelEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServiceEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/IdentifierRelationDAO.java

Resolves #344

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/webhooks/ManagementWebhookHandler.java

Update menus on nav_menu_item webhook

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/linkedevents/LinkedEventsTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/linkedevents/updaters/LinkedEvenstEventEntityUpdater.java
src/test/java/fi/otavanopisto/kuntaapi/test/AbstractIntegrationTest.java

Implemented place and image support for LinkedEvents

---

.travis.yml
pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/discover/EntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/discover/IdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMOrganizationContentsEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/vcard/VCardEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/TaskQueueDistributor.java
src/main/resources/fi/otavanopisto/kuntaapi/server/integrations/casem/content-board.ftlh
src/main/resources/fi/otavanopisto/kuntaapi/server/integrations/casem/content-meeting-item.ftlh
src/main/resources/fi/otavanopisto/kuntaapi/server/integrations/casem/content-meeting.ftlh
travis.sh

Add meta-datas into CaseM pages

---

src/main/resources/fi/otavanopisto/kuntaapi/server/integrations/casem/content-board.ftlh
src/main/resources/fi/otavanopisto/kuntaapi/server/integrations/casem/content-meeting-item.ftlh
src/main/resources/fi/otavanopisto/kuntaapi/server/integrations/casem/content-meeting.ftlh
travis.sh

Fixed issue #361

---

.travis.yml
pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/ContactController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/PageController.java
src/main/java/fi/otavanopisto/kuntaapi/server/discover/EntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/discover/IdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/id/AbstractIdFactory.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/AbstractIndexHander.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/ContactSearcher.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexRemoveContact.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexableContact.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/ServiceSearcher.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ContactSortBy.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/vcard/VCardConsts.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/vcard/VCardEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/vcard/VCardIdFactory.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/vcard/VCardTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/TaskQueueDistributor.java
src/test/java/fi/otavanopisto/kuntaapi/test/AbstractIntegrationTest.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/management/PageTestsIT.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/management/PostTestsIT.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/ptv/OrganizationsTestsIT.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/ptv/ServiceChannelsTestsIT.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/ptv/ServicesTestsIT.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/vcard/VCardTestsIT.java
src/test/resources/vcard/test-removed.vcard
src/test/resources/vcard/test.vcard
travis.sh

Feature #363 search contacts

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/images/ScaledImageStore.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/AttachmentData.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/linkedevents/LinkedEventsEventProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/linkedevents/updaters/LinkedEvenstEventEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/AbstractAttachmentImageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/AbstractManagementProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementAnnouncementEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementBannerProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsArticleEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementNewsProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementTileProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytEventProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/mikkelinyt/MikkeliNytImageLoader.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/ptv/OrganizationsTestsIT.java

Added support for persisting prescaled into the disk

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/FileController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/PageController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/FileProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/PageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMFileProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMPageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java

Added support for deleting casem files

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/FileController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/PageController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/FileProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/PageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMFileProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/casem/CaseMPageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java

Hotfix #371 deletes

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/linkedevents/LinkedEventsConsts.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/linkedevents/LinkedEventsTranslator.java

Fixed issue #376

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/TaskController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/tasks/GtfsAgencyEntityTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/tasks/GtfsRouteEntityTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/tasks/GtfsScheduleEntityTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/tasks/GtfsStopEntityTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/tasks/GtfsStopTimeEntityTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/gtfs/tasks/GtfsTripEntityTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/kuntarekry/tasks/AbstractKuntaRekryJobTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/kuntarekry/tasks/KuntaRekryJobEntityTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/kuntarekry/tasks/KuntaRekryRemoveJobTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/tasks/AbstractServiceChannelTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/tasks/ElectronicServiceChannelRemoveTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/tasks/PhoneServiceChannelRemoveTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/tasks/PrintableFormServiceChannelRemoveTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/tasks/ServiceChannelUpdateTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/tasks/ServiceLocationServiceChannelRemoveTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/tasks/WebPageServiceChannelRemoveTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/tilannehuone/tasks/TilannehuoneEmergencyEntityTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/TaskDAO.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/TaskQueueDAO.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/model/Task.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/AbstractTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/IdTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/OrganizationEntityUpdateTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/ServiceEntityUpdateTask.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/TaskQueueDistributor.java
src/main/resources/fi/otavanopisto/kuntaapi/server/liquibase/changelog.xml

Feature #379 unique ids

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/TaskController.java

Added SQL Exception handling into task create method

---

src/main/java/fi/otavanopisto/kuntaapi/server/rest/SlowRequestFilter.java
src/main/resources/slow-request-filter.properties

Added support for excluding certain paths from slow request filter

---

src/main/java/fi/otavanopisto/kuntaapi/server/index/ContactSearcher.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexableContact.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ContactSortBy.java

Resolves #388

---

src/main/java/fi/otavanopisto/kuntaapi/server/rest/SystemRESTService.java

system utils

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/ServiceController.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexRemoveDeprecatedService.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexRemoveService.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexableService.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/ServiceSearcher.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServiceEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/CodesApiImpl.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/ServicesApiImpl.java
src/main/java/fi/otavanopisto/kuntaapi/server/security/SecurityFilter.java
src/main/java/fi/otavanopisto/kuntaapi/server/utils/LocalizationUtils.java
src/test/java/fi/otavanopisto/kuntaapi/test/AbstractIntegrationTest.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/ptv/ServicesTestsIT.java

Added support for filtering services by service channel ids

---

src/main/java/fi/otavanopisto/kuntaapi/server/rest/SystemRESTService.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/ptv/ServicesTestsIT.java

Feature #414 service update endpoint

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/ServiceController.java
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/TaskController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ServiceProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceChannelProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/translation/KuntaApiPtvTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/translation/PtvOutPtvInTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/translation/PtvTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvOrganizationEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/persistence/dao/AbstractDAO.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/ServicesApiImpl.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/SystemRESTService.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/AbstractTaskQueue.java
src/main/java/fi/otavanopisto/kuntaapi/server/tasks/TaskListener.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/ptv/OrganizationsTestsIT.java

Feature #417 update ptv services

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/ServiceController.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/ElectronicServiceChannelSearcher.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexRemoveElectronicServiceChannel.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexableElectronicServiceChannel.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ElectronicServiceChannelSortBy.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ServiceChannelProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceChannelProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/translation/KuntaApiPtvTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/translation/PtvOutPtvInTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/translation/PtvTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/AbstractPtvServiceChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServiceChannelEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/ElectronicServiceChannelsApiImpl.java
src/test/java/fi/otavanopisto/kuntaapi/test/AbstractIntegrationTest.java

Added support for search and update electronic service channels

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/client/PtvApi.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/translation/KuntaApiPtvTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/translation/PtvOutPtvInTranslator.java

Feature #423 service service channels

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/ServiceController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ServiceChannelProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceChannelProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/translation/KuntaApiPtvTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/translation/PtvOutPtvInTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/PhoneServiceChannelsApiImpl.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/PrintableFormServiceChannelsApiImpl.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/ServiceLocationServiceChannelsApiImpl.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/WebPageServiceChannelsApiImpl.java

Added support for updating ptv phone service channels

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/ServiceController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ServiceChannelProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceChannelProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/translation/KuntaApiPtvTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/translation/PtvOutPtvInTranslator.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/PrintableFormServiceChannelsApiImpl.java

Feature #429 update ptv printable forms

---

src/main/java/fi/otavanopisto/kuntaapi/server/discover/AbstractUpdater.java

Changed updater monitor thresholds

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/webhooks/ManagementWebhookHandler.java

Added "draft" status handler into management webhooks

---

src/main/java/fi/otavanopisto/kuntaapi/server/rest/SystemRESTService.java

Added utility methods for updating service channels

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceProvider.java

Changed ptv service update to use PTV id instead Kunta API id

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceProvider.java

Removed unnecessary listing of services service channels

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/PtvServiceProvider.java

Send empty list instead of null channel relations

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/IdentifierController.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/SystemRESTService.java

Resolves #447

---

.gitignore
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvOrganizationIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServiceChannelIdUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvServiceIdUpdater.java
src/test/java/fi/otavanopisto/kuntaapi/test/AbstractPtvMocker.java

Fixes #452 organization id off by one

Fixes #452 organization id off by one

---

src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexRemoveDeprecatedPage.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexablePage.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java

Fixes #454 separate elastic fields for languages in pages

Fixes #454 separate elastic fields for languages in pages

---

src/main/java/fi/otavanopisto/kuntaapi/server/controllers/PageController.java
src/main/java/fi/otavanopisto/kuntaapi/server/discover/AbstractUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexRemoveDeprecatedPage.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/IndexablePage.java
src/main/java/fi/otavanopisto/kuntaapi/server/index/PageSearcher.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/PageSortBy.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvAccessTokenUpdater.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/OrganizationsApiImpl.java
src/main/java/fi/otavanopisto/kuntaapi/server/rest/SystemRESTService.java

Hotfix #456 pages need to wait for sync to get reordered by menu order

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/webhooks/ManagementWebhookHandler.java

Added support for webhook post status expiration, future, private and

---

src/main/java/fi/otavanopisto/kuntaapi/server/index/search/NewsArticleSearcher.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/management/PostTestsIT.java

Fixed issue #465

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/linkedevents/LinkedEventsEventProvider.java

Fixed issue #474

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/ptv/updaters/PtvAccessTokenUpdater.java

Fixed issue #486

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/management/PageTestsIT.java
src/test/resources/management/pages/567.json

Changed management page updated to unescape HTML entities

---

src/main/java/fi/otavanopisto/kuntaapi/server/integrations/management/ManagementPageEntityUpdater.java

Moved html unescape into page index task

---

src/main/java/fi/otavanopisto/kuntaapi/server/images/ImageScaler.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/unit/images/ImageScalerTest.java

Fixed issue #495

---

src/main/resources/fi/metatavu/kuntaapi/server/liquibase/changelog.xml

Added migration script for purging tasks

---

src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/PtvConsts.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/updaters/PtvOrganizationIdUpdater.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/updaters/PtvOrganizationPriorityIdUpdater.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/updaters/PtvServiceChannelIdUpdater.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/updaters/PtvServiceChannelPriorityIdUpdater.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/updaters/PtvServiceIdUpdater.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/updaters/PtvServicePriorityIdUpdater.java
src/test/java/fi/metatavu/kuntaapi/test/server/integration/ptv/PhoneServiceChannelInTestsIT.java

Fixed issue #526

---

pom.xml
src/main/java/fi/metatavu/kuntaapi/server/controllers/TaskController.java
src/main/java/fi/metatavu/kuntaapi/server/persistence/dao/AbstractDAO.java
src/main/java/fi/metatavu/kuntaapi/server/persistence/model/ArchivedIdentifier.java
src/main/java/fi/metatavu/kuntaapi/server/persistence/model/Identifier.java
src/main/java/fi/metatavu/kuntaapi/server/persistence/model/OrganizationExternalAccessToken.java
src/main/java/fi/metatavu/kuntaapi/server/persistence/model/OrganizationSetting.java
src/main/java/fi/metatavu/kuntaapi/server/persistence/model/StoredBinaryResource.java
src/main/java/fi/metatavu/kuntaapi/server/persistence/model/StoredResource.java
src/main/java/fi/metatavu/kuntaapi/server/persistence/model/SystemSetting.java
src/main/java/fi/metatavu/kuntaapi/server/persistence/model/Task.java
src/main/java/fi/metatavu/kuntaapi/server/persistence/model/TaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/persistence/model/clients/Client.java
travis-before-script.sh

Feature #515 wildfly 14

---

pom.xml
src/main/java/fi/otavanopisto/kuntaapi/server/controllers/JobController.java
src/main/java/fi/otavanopisto/kuntaapi/server/integrations/JobProvider.java
src/main/java/fi/otavanopisto/kuntaapi/server/jobs/AbstractJobComparator.java
src/main/java/fi/otavanopisto/kuntaapi/server/jobs/PriorityTitleJobComparator.java
src/main/java/fi/otavanopisto/kuntaapi/server/jobs/PublicationEndComparator.java
src/main/java/fi/otavanopisto/kuntaapi/server/jobs/PublicationStartComparator.java
src/test/java/fi/otavanopisto/kuntaapi/test/server/integration/kuntarekry/KuntaRekryTestsIT.java
src/test/resources/kuntarekry/feed.xml
travis-before-script.sh

Added support for prioritizing jobs by title

---

docker/entrypoint.sh
docker/liquibase/settings.sql
es-docker/entrypoint.sh
pom.xml
src/main/java/fi/metatavu/kuntaapi/server/integrations/gtfs/tasks/GtfsAgencyTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/gtfs/tasks/GtfsRouteTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/gtfs/tasks/GtfsScheduleTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/gtfs/tasks/GtfsStopTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/gtfs/tasks/GtfsStopTimeTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/gtfs/tasks/GtfsTripTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/kuntarekry/tasks/KuntaRekryJobTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/management/tasks/AnnouncementIdTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/management/tasks/BannerIdTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/management/tasks/MenuIdTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/management/tasks/NewsArticleIdTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/management/tasks/PageIdTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/PtvServiceChannelProvider.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/PtvServiceProvider.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/tasks/OrganizationIdTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/tasks/ServiceChannelTasksQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/tasks/ServiceIdTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/translation/PtvTranslator.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/updaters/PtvServiceChannelEntityDiscoverJob.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/updaters/PtvServiceEntityDiscoverJob.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/tilannehuone/tasks/TilannehuoneEmergencyTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/tpt/tasks/TptJobTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/tasks/jms/AbstractJmsJob.java
src/main/java/fi/metatavu/kuntaapi/server/tasks/jms/AbstractJmsTaskQueue.java
src/main/java/fi/metatavu/kuntaapi/server/tasks/jms/AbstractRespondingJmsJob.java
src/main/java/fi/metatavu/kuntaapi/server/tasks/jms/DefaultJmsTaskQueue.java

Hotfix #551 waiting jms tasks

---

src/main/java/fi/metatavu/kuntaapi/server/integrations/GenericHttpClient.java

Support charset defition in xml content type header

---

src/main/java/fi/metatavu/kuntaapi/server/integrations/environmentalwarnings/fmiweatheralerts/wfs/Feature.java

Resolves #575

---

src/main/java/fi/metatavu/kuntaapi/server/integrations/management/ManagementNewsArticleEntityDiscoverJob.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/management/client/ManagementApi.java

Fixed issue #578

---

src/main/java/fi/metatavu/kuntaapi/server/integrations/management/ManagementNewsArticleEntityDiscoverJob.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/management/client/ManagementApi.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/ptv/updaters/PtvAccessTokenDiscoverJob.java

Hotfix 580 ptv trn access tokens

---

src/main/java/fi/metatavu/kuntaapi/server/controllers/IdentifierRelationController.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/linkedevents/LinkedEventsEventProvider.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/linkedevents/updaters/LinkedEvenstEventEntityDiscoverJob.java
src/test/java/fi/metatavu/kuntaapi/test/AbstractIntegrationTest.java
src/test/java/fi/metatavu/kuntaapi/test/AbstractTest.java
src/test/java/fi/metatavu/kuntaapi/test/LinkedEventsEventMocker.java
src/test/java/fi/metatavu/kuntaapi/test/server/integration/linkedevents/LinkedEventsTestsIT.java
src/test/java/fi/metatavu/kuntaapi/test/server/integration/ptv/OrganizationsTestsIT.java
src/test/java/fi/metatavu/kuntaapi/test/server/integration/tilannehuone/TilannehuoneTestsIT.java
src/test/resources/linkedevents/events/mantyharju_pm-maastojuoksukilpailut-la-27_image3.json
src/test/resources/linkedevents/images/2.json
src/test/resources/linkedevents/images/3.json

Hotfix 582 linked events images

---

src/main/java/fi/metatavu/kuntaapi/server/integrations/management/ManagementNewsArticleEntityDiscoverJob.java

Fixed issue #585

---

pom.xml
src/main/java/fi/metatavu/kuntaapi/server/integrations/management/ManagementPageEntityDiscoverJob.java
src/main/java/fi/metatavu/kuntaapi/server/integrations/management/ManagementTranslator.java

Added support for site root page page meta

---

src/main/java/fi/metatavu/kuntaapi/server/integrations/management/ManagementPageEntityDiscoverJob.java

Changed management page indexing to strip soft hyphens before indexing

---

src/main/java/fi/metatavu/kuntaapi/server/integrations/kuntarekry/KuntaRekryJob.java

Ignored unknown properties from kunta rekry job
